### ISSUE TITLE
deleteing acl entries seems to delete the entire ACL.

### ISSUE THREAD

**Issue by mobig** [netascode/terraform-provider-iosxe#105]
When deleting an ACL entry, the resource is deleting the entire ACL. i have to run terraform apply a second time to get the ACL back minus the deleted entry. this seems to be the case with standard and extended access lists.
```
#main.tf

resource "iosxe_access_list_standard" "example" {
  for_each = {for acl in local.router_acls_standard : acl.key => acl}
  device   = each.value.device
  name     = each.value.name
  entries  = [
    {
      sequence           = each.value.sequence
      remark             = each.value.remark == "" ? null : each.value.remark
      deny_prefix        = each.value.deny_prefix == "" ? null : each.value.deny_prefix
      deny_prefix_mask   = each.value.deny_prefix_mask == "" ? null : each.value.deny_prefix_mask
      permit_prefix      = each.value.permit_prefix == "" ? null : each.value.permit_prefix
      permit_prefix_mask = each.value.permit_prefix_mask == "" ? null : each.value.permit_prefix_mask
      permit_any         = each.value.permit_any == "" ? null : each.value.permit_any
      permit_host        = each.value.permit_host == "" ? null : each.value.permit_host
    }
  ]
}
```
```
#locals.tf

  router_acls_standard = flatten([
    for router in local.routers : [
      for acl in router.acls_standard : {
        key                = "${router.name}-${acl.name}-${acl.sequence}"
        device             = router.name
        name               = acl.name
        sequence           = acl.sequence
        remark             = acl.remark
        deny_prefix        = acl.deny_prefix
        deny_prefix_mask   = acl.deny_prefix_mask
        permit_any         = acl.permit_any
        permit_host        = acl.permit_host
        permit_prefix      = acl.permit_prefix
        permit_prefix_mask = acl.permit_prefix_mask
      }
    ]
  ])
```

**Comment by mobig** [comment]
this issue appears to be happening with prefix lists and route-maps as well.

**Comment by danischm** [comment]
You are using a resource per ACL entry, you need to use a resource per ACL and create entries within that resource:

```
resource "iosxe_access_list_standard" "example" {
  name = "SACL1"
  entries = [
    {
      sequence         = 10
      remark           = "Description"
      deny_prefix      = "10.0.0.0"
      deny_prefix_mask = "0.0.0.255"
    },
    {
      sequence         = 20
      remark           = "Description2"
      deny_prefix      = "11.0.0.0"
      deny_prefix_mask = "0.0.0.255"
    }
  ]
}
```

**Comment by mobig** [comment]
do they have to be added manually like this or is there a way to pull them out with a loop or use a locals var map? i'd like to ingest these from csv or yaml

**Comment by mobig** [comment]
i've tried to do the following with no luck, the provider just crashes. any help you could give would be appreciated greatly 
```
# locals.tf

  router_acls_standard = {
    for router in local.routers : router.name => [
        for acl in router.acls_standard : {
          sequence           = acl.sequence
          remark             = acl.remark
          deny_prefix        = acl.deny_prefix
          deny_prefix_mask   = acl.deny_prefix_mask
        }
      ]
    }
```
```
#main.tf

resource "iosxe_access_list_standard" "example" {
  for_each = {for router in local.routers : router.name => router}
  device   = each.value.url
  name     = each.value.name
  entries  = [
    for entry in local.router_acls_standard[each.value.name] :{
        sequence           = entry.sequence
        remark             = entry.remark == "" ? null : entry.remark
        deny_prefix        = entry.deny_prefix == "" ? null : entry.deny_prefix
        deny_prefix_mask   = entry.deny_prefix_mask == "" ? null : entry.deny_prefix_mask
    }
  ]
}
```
```
#router_acls_standard output

"Site-01" = [
    {
      "deny_prefix" = "10.0.0.0"
      "deny_prefix_mask" = "0.0.0.255"
      "remark" = "Deny traffic from 10.0.0.0/8"
      "sequence" = "10"
    },
    {
      "deny_prefix" = "10.0.0.0"
      "deny_prefix_mask" = "0.0.0.255"
      "remark" = "Deny traffic from 10.0.0.0/8"
      "sequence" = "20"
    },
  ]
  "Site-02" = [
    {
      "deny_prefix" = "10.0.0.0"
      "deny_prefix_mask" = "0.0.0.255"
      "remark" = "Deny traffic from 10.0.0.0/8"
      "sequence" = "10"
    },
  ]
```
```
# stack trace

Stack trace from the terraform-provider-iosxe_v0.1.15.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x8 pc=0xf9f8be]

goroutine 571 [running]:
github.com/netascode/go-restconf.(*Client).Discovery(0x0, {0x1?, 0xaf0d9e?, 0xc000c96460?})
        github.com/netascode/go-restconf@v0.1.9/client.go:395 +0x3e
github.com/netascode/go-restconf.(*Client).PatchData(0x20?, {0xc0003dd450, 0x43}, {0xc0002165b0, 0xc4}, {0x0, 0x0, _})
        github.com/netascode/go-restconf@v0.1.9/client.go:510 +0x9f
github.com/netascode/terraform-provider-iosxe/internal/provider.(*AccessListStandardResource).Create(0xc000116080, {0x155f320, 0xc00096a180}, {{{{0x1564190, 0xc0010d6d50}, {0x12bea20, 0xc00096b9b0}}, {0x15664e8, 0xc0000ff7c0}}, {{{0x1564190, ...}, ...}, ...}, ...}, ...)
        github.com/netascode/terraform-provider-iosxe/internal/provider/resource_iosxe_access_list_standard.go:151 +0x43f
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0002331e0, {0x155f320, 0xc00096a180}, 0xc0004ef360, 0xc0004ef300)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_createresource.go:97 +0x5b8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x155f320?, {0x155f320, 0xc00096a180}, 0xc000bc61e0, 0xc0004ef4d0)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_applyresourcechange.go:54 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0002331e0, {0x155f320?, 0xc00047dfb0?}, 0xc000bc6190)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_applyresourcechange.go:52 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00022f040, {0x155f320?, 0xc00047d7d0?}, 0xc000312070)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x137bb40?, 0xc00022f040}, {0x155f320, 0xc00047d7d0}, 0xc000312000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:419 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028a1e0, {0x1564a78, 0xc0000ebd40}, 0xc000a4e000, 0xc0003ec1b0, 0x1a4d920, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00028a1e0, {0x1564a78, 0xc0000ebd40}, 0xc000a4e000, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-iosxe_v0.1.15.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by danischm** [comment]
Can you share the content of the `local.routers` variable?

**Comment by mobig** [comment]
inside the locals file, each router has a dir with configuration that's specific to each router.
```
locals {
  routers = [
    {
      name                      = "Site-01"
      url                       = "https://192.168.0.152"
      vrf_config                = yamldecode(file("${path.module}/configs/Site-04_01/vrf_config.yaml"))
      ethernet_interface_config = csvdecode(file("${path.module}/configs/Site-04_01/ethernet_interface_config.csv"))
      loopback_interface_config = csvdecode(file("${path.module}/configs/Site-04_01/loopback_interface_config.csv"))
      netflow_config            = csvdecode(file("${path.module}/configs/Site-04_01/netflow_config.csv"))
      track_objects             = csvdecode(file("${path.module}/configs/Site-04_01/track_objects.csv"))
      bgp_config                = yamldecode(file("${path.module}/configs/Site-04_01/bgp_config.yaml"))
      tftp_source               = csvdecode(file("${path.module}/configs/Site-04_01/tftp_source.csv"))
      static_routes             = csvdecode(file("${path.module}/configs/Site-04_01/static_routes.csv"))
      acls_extended             = csvdecode(file("${path.module}/configs/Site-04_01/ACLs_extended.csv"))
      acls_standard             = csvdecode(file("${path.module}/configs/Site-04_01/ACLs_standard.csv"))
      prefix_lists              = csvdecode(file("${path.module}/configs/Site-04_01/prefix_lists.csv"))
      logging                   = yamldecode(file("${path.module}/configs/global/logging.yaml"))
      route_maps_config         = yamldecode(file("${path.module}/configs/Site-04_01/route-maps.yaml"))
      tacacs_config             = yamldecode(file("${path.module}/configs/global/tacacs_config.yaml"))
      snmp_config               = yamldecode(file("${path.module}/configs/global/snmp_config.yaml"))
      vty_line_config           = csvdecode(file("${path.module}/configs/Site-04_01/vty_line_config.csv"))
      bgp_neighbors             = yamldecode(file("${path.module}/configs/Site-04_01/bgp_neighbors.yaml"))
      clock_config              = yamldecode(file("${path.module}/configs/global/clock_config.yaml"))
    },
    {
      name                      = "Site-02"
      url                       = "https://192.168.0.153"
      vrf_config                = yamldecode(file("${path.module}/configs/Site-04_02/vrf_config.yaml"))
      ethernet_interface_config = csvdecode(file("${path.module}/configs/Site-04_02/ethernet_interface_config.csv"))
      loopback_interface_config = csvdecode(file("${path.module}/configs/Site-04_02/loopback_interface_config.csv"))
      netflow_config            = csvdecode(file("${path.module}/configs/Site-04_02/netflow_config.csv"))
      track_objects             = csvdecode(file("${path.module}/configs/Site-04_02/track_objects.csv"))
      bgp_config                = yamldecode(file("${path.module}/configs/Site-04_02/bgp_config.yaml"))
      tftp_source               = csvdecode(file("${path.module}/configs/Site-04_02/tftp_source.csv"))
      static_routes             = csvdecode(file("${path.module}/configs/Site-04_02/static_routes.csv"))
      acls_extended             = csvdecode(file("${path.module}/configs/Site-04_02/ACLs_extended.csv"))
      acls_standard             = csvdecode(file("${path.module}/configs/Site-04_02/ACLs_standard.csv"))
      prefix_lists              = csvdecode(file("${path.module}/configs/Site-04_02/prefix_lists.csv"))
      logging                   = yamldecode(file("${path.module}/configs/global/logging.yaml"))
      route_maps_config         = yamldecode(file("${path.module}/configs/Site-04_02/route-maps.yaml"))
      tacacs_config             = yamldecode(file("${path.module}/configs/global/tacacs_config.yaml"))
      snmp_config               = yamldecode(file("${path.module}/configs/global/snmp_config.yaml"))
      vty_line_config           = csvdecode(file("${path.module}/configs/Site-04_02/vty_line_config.csv"))
      bgp_neighbors             = yamldecode(file("${path.module}/configs/Site-04_02/bgp_neighbors.yaml"))
      clock_config              = yamldecode(file("${path.module}/configs/global/clock_config.yaml"))
    }
  ]
```
as you can see, I'm using csvdecode on the acls_standard.csv file. this is what that file looks like:
```
name,"sequence","remark","deny_prefix","deny_prefix_mask","permit_prefix","permit_prefix_mask","permit_any","permit_host"
"example-acl","10","Deny traffic from 10.0.0.0/8","10.0.0.0","0.0.0.255","","","",""
"example-acl","20","Deny traffic from 10.0.0.0/8","10.0.0.0","0.0.0.255","","","",""
```
that file is processed into the `router_acls_standard` map (also in locals):
```
  router_acls_standard = {
    for router in local.routers : router.name => [
        for acl in router.acls_standard : {
          sequence           = acl.sequence
          remark             = acl.remark
          deny_prefix        = acl.deny_prefix
          deny_prefix_mask   = acl.deny_prefix_mask
        }
      ]
    }
```
and then i'm running the the following in my main.tf:
```
resource "iosxe_access_list_standard" "example" {
  for_each = {for router in local.routers : router.name => router}
  device   = each.value.url
  name     = each.value.name
  entries  = [
    for entry in local.router_acls_standard[each.value.name] :{
        sequence           = entry.sequence
        remark             = entry.remark == "" ? null : entry.remark
        deny_prefix        = entry.deny_prefix == "" ? null : entry.deny_prefix
        deny_prefix_mask   = entry.deny_prefix_mask == "" ? null : entry.deny_prefix_mask
    }
  ]
}
```

**Comment by danischm** [comment]
Thanks, could you please also share your provider configuration?

**Comment by mobig** [comment]
here you go:
```
terraform {
  required_providers {
    iosxe = {
      source  = "netascode/iosxe"
      version = "0.1.15"
    }
  }
}

provider "iosxe" {
  username = "<omitted>"
  password = "<omitted>"
  devices  = local.routers
  retries  = 20
}
```

**Comment by mobig** [comment]
Hate to be a bother. Any chance you’ve had an opportunity to look at this? Thank you again for your time.

**Comment by danischm** [comment]
It looks like there is an error in your Terraform code. The `device` attribute of the resource must be a device name not a device URL.

**Comment by danischm** [comment]
A check has been added in the latest release to verify if a device with the provided name exists.
